enable = false
connection = "/tmp/syndication.db"

[database]

  [database.sqlite]
    enable = true
    connection = "/tmp/syndication.db"

[server]
  auth_secret = "secret_cat"
  auth_secret_file_path = ""
  enable_tls = false
  enable_http_requests_log = false
  enable_panic_print_stack = false
  domain = ""
  cert_cache_dir = ""
  max_shutdown_time = 0
  http_port = 0
  tls_port = 0
  shutdown_timeout = "5s"
  api_key_expiration = "72h"

[sync]
  time = 0001-01-01T00:00:00Z
  interval = "5m"

[admin]
  socket_path = ""
  max_connections = 0
